const POKE_FETCH_LIST = 'POKE_FETCH_LIST';
const POKE_ADD_LIST = 'POKE_ADD_LIST';
const POKE_FETCH_ERROR = 'POKE_FETCH_ERROR';
const POKE_FETCH_LOADING = 'POKE_FETCH_LOADING';

export { POKE_FETCH_LIST, POKE_ADD_LIST, POKE_FETCH_ERROR, POKE_FETCH_LOADING };

const KEY_STORAGE_TOKEN = 'KEY_STORAGE_TOKEN';
const KEY_STORAGE_ENTITY = 'KEY_STORAGE_ENTITY';
const KEY_STORAGE_LOCATION = 'KEY_STORAGE_LOCATION';
export { KEY_STORAGE_TOKEN, KEY_STORAGE_ENTITY, KEY_STORAGE_LOCATION };

const AUTH_LOGIN = 'AUTH_LOGIN';
const AUTH_LOGOUT = 'AUTH_LOGOUT';
const AUTH_ERROR = 'AUTH_ERROR';
const AUTH_LOADING = 'AUTH_LOADING';
const AUTH_SET_TOKEN = 'AUTH_SET_TOKEN';
const AUTH_FORGOT_PASS = 'AUTH_FORGOT_PASS';
const AUTH_REGISTER = 'AUTH_REGISTER';
const AUTH_CLEAR_ALL_STATE = 'AUTH_CLEAR_ALL_STATE';

export {
  AUTH_LOGIN,
  AUTH_LOGOUT,
  AUTH_ERROR,
  AUTH_LOADING,
  AUTH_SET_TOKEN,
  AUTH_FORGOT_PASS,
  AUTH_REGISTER,
  AUTH_CLEAR_ALL_STATE,
};

const USER_LOADING = 'USER_LOADING';
const USER_GET = 'USER_GET';
const USER_SET_LIST = 'USER_SET_LIST';
const USER_GET_ME = 'USER_GET_ME';
const USER_SET_ME = 'USER_SET_ME';
const USER_SET_ENTITY = 'USER_SET_ENTITY';
const USER_SET_LOCATION = 'USER_SET_LOCATION';
const USER_SET_LOCATION_LIST = 'USER_SET_LOCATION_LIST';
const USER_GET_LOCATION_LIST = 'USER_GET_LOCATION_LIST';
const USER_CHANGE_PASSWORD = 'USER_CHANGE_PASSWORD';
const USER_CHANGE_PROFILE = 'USER_CHANGE_PROFILE';
const USER_GET_SUBSCRIPTION = 'USER_GET_SUBSCRIPTION';
const USER_SET_SUBSCRIPTION = 'USER_SET_SUBSCRIPTION';
const USER_SET_SUBSCRIPTION_STATUS = 'USER_SET_SUBSCRIPTION_STATUS';

export {
  USER_LOADING,
  USER_GET,
  USER_SET_LIST,
  USER_GET_ME,
  USER_SET_ME,
  USER_SET_ENTITY,
  USER_SET_LOCATION,
  USER_CHANGE_PASSWORD,
  USER_CHANGE_PROFILE,
  USER_SET_LOCATION_LIST,
  USER_GET_LOCATION_LIST,
  USER_GET_SUBSCRIPTION,
  USER_SET_SUBSCRIPTION,
  USER_SET_SUBSCRIPTION_STATUS,
};

const ENTITY_LOADING = 'ENTITY_LOADING';
const ENTITY_GET = 'ENTITY_GET';
const ENTITY_GET_BY_ID = 'ENTITY_GET_BY_ID';
const ENTITY_SET_LIST = 'ENTITY_SET_LIST';
const ENTITY_GET_MEMBER = 'ENTITY_GET_MEMBER';
const ENTITY_SET_MEMBER = 'ENTITY_SET_MEMBER';

export {
  ENTITY_LOADING,
  ENTITY_GET,
  ENTITY_GET_BY_ID,
  ENTITY_SET_LIST,
  ENTITY_GET_MEMBER,
  ENTITY_SET_MEMBER,
};

const ACTIVITY_TYPE_LOADING = 'ACTIVITY_TYPE_LOADING';
const ACTIVITY_TYPE_GET = 'ACTIVITY_TYPE_GET';
const ACTIVITY_TYPE_SET_LIST = 'ACTIVITY_TYPE_SET_LIST';

export { ACTIVITY_TYPE_LOADING, ACTIVITY_TYPE_GET, ACTIVITY_TYPE_SET_LIST };

const ACTIVITY_LOADING = 'ACTIVITY_LOADING';
const ACTIVITY_GET = 'ACTIVITY_GET';
const ACTIVITY_SET_LIST = 'ACTIVITY_SET_LIST';
const ACTIVITY_GET_RECENT = 'ACTIVITY_GET_RECENT';
const ACTIVITY_SET_RECENT_LIST = 'ACTIVITY_SET_RECENT_LIST';

export {
  ACTIVITY_LOADING,
  ACTIVITY_GET,
  ACTIVITY_SET_LIST,
  ACTIVITY_GET_RECENT,
  ACTIVITY_SET_RECENT_LIST,
};

const EVENT_LOADING = 'EVENT_LOADING';
const EVENT_GET = 'EVENT_GET';
const EVENT_SET_LIST = 'EVENT_SET_LIST';
const EVENT_INSERT_DATA = 'EVENT_INSERT_DATA';
const EVENT_UPDATE_DATA = 'EVENT_UPDATE_DATA';
const EVENT_SCAN = 'EVENT_SCAN';
const EVENT_GET_BY_ID = 'EVENT_GET_BY_ID';

export {
  EVENT_LOADING,
  EVENT_GET,
  EVENT_SET_LIST,
  EVENT_INSERT_DATA,
  EVENT_UPDATE_DATA,
  EVENT_SCAN,
  EVENT_GET_BY_ID,
};

const LOCATION_LOADING = 'LOCATION_LOADING';
const LOCATION_GET = 'LOCATION_GET';
const LOCATION_SET_LIST = 'LOCATION_SET_LIST';

export { LOCATION_LOADING, LOCATION_GET, LOCATION_SET_LIST };

const SURVEY_GET_BY_ID = 'SURVEY_GET_BY_ID';
const SURVEY_SET_LIST = 'SURVEY_SET_LIST';

export { SURVEY_GET_BY_ID, SURVEY_SET_LIST };

const PRODUCT_GET_BY_ID = 'PRODUCT_GET_BY_ID'
const PRODUCT_SET_LIST = 'PRODUCT_SET_LIST'

export { PRODUCT_GET_BY_ID, PRODUCT_SET_LIST }